// flow-typed signature: 6165818b141b777e3aaa069b77923130
// flow-typed version: <<STUB>>/@jcoreio/condition-solano_v^1.0.0/flow_v0.61.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@jcoreio/condition-solano'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@jcoreio/condition-solano' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@jcoreio/condition-solano/lib/resolve-config' {
  declare module.exports: any;
}

// Filename aliases
declare module '@jcoreio/condition-solano/index' {
  declare module.exports: $Exports<'@jcoreio/condition-solano'>;
}
declare module '@jcoreio/condition-solano/index.js' {
  declare module.exports: $Exports<'@jcoreio/condition-solano'>;
}
declare module '@jcoreio/condition-solano/lib/resolve-config.js' {
  declare module.exports: $Exports<'@jcoreio/condition-solano/lib/resolve-config'>;
}
